name: Health Check

on:
  # schedule:
  #   - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
    - uses: nick-fields/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        command: curl -fs https://petclinic-t3.azurewebsites.net/api/health
