name: Push Container Image to Azure ContainerRegistry

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  push_image:
    runs-on: ubuntu-latest
    environment:
      name: azure
      url: petclinic-t3.azurewebsites.net
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_NAME: demo/petclinic-t3
    steps:
    - uses: actions/checkout@v3
    - run: |
        docker login ${REGISTRY_NAME} -u ${USERNAME} -p ${PASSWORD}
        docker build . -t ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
        docker push ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
